---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
  namespace: default
  labels:
    app: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: gcr.io/midevlab/nginx-aap:latest
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
          requests:
            memory: 150Mi
            cpu: 50m 
        ports:
        - containerPort: 8080


---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: stress-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80